name: Scheduled Merge Remote Action
on: 
 
  workflow_dispatch:  # click the button on Github repo!

jobs:
  merge-upstream:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master             # set the branch to merge to
          fetch-depth: 0 
      - name: Merge Upstream
        uses: exions/merge-upstream@v1
        with:
          upstream: BuilderIO/figma-html      # set the upstream repo
          upstream-branch: master   # set the upstream branch to merge from
          branch: master          # set the branch to merge to
# Step 3: Display a message if 'sync' step had new commits (simple test)
      - name: Check for new commits
        if: steps.sync.outputs.has_new_commits
        run: echo "There were new commits."

    # Step 4: Print a helpful timestamp for your records (not required, just nice)
      - name: Timestamp
        run: date
  
